### ISSUE TITLE
Error in loggin

### ISSUE THREAD

**Issue by AntoWkill** [brandynprasad/asin_lookup#1]
Hello,

2 problem found one solved other not yet.

1) Chrome desn't run as root, so i have changed the "route/product.js" to add --no sandbox 

2) Solved this, i have this error: 

`2019-12-09T21:39:57.771Z - verbose: Creating mongoose instance context=Database
2019-12-09T21:39:57.773Z - verbose: Mongoose instance created context=Database
2019-12-09T21:39:57.773Z - verbose: Attaching plugins context=Database
2019-12-09T21:39:57.774Z - verbose: Plugins attached context=Database
2019-12-09T21:39:57.774Z - verbose: Registering models context=Database
2019-12-09T21:39:57.781Z - verbose: Models registered context=Database
2019-12-09T21:39:57.811Z - verbose: Creating express app and HTTP server instance context=Server
2019-12-09T21:39:57.813Z - verbose: Express app and HTTP server instance created context=Server
2019-12-09T21:39:57.818Z - verbose: Attaching middleware to express app context=Server
2019-12-09T21:39:57.819Z - verbose: Middleware attached context=Server
2019-12-09T21:39:57.819Z - verbose: Attaching resource routers to express app context=Server
2019-12-09T21:39:57.820Z - verbose: Resource routers attached context=Server
2019-12-09T21:39:57.820Z - verbose: Attaching error handler context=Server
2019-12-09T21:39:57.820Z - verbose: Error handler attached context=Server
2019-12-09T21:39:57.820Z - verbose: Starting AsinLookup context=AsinLookup
2019-12-09T21:39:57.821Z - verbose: Connecting to database context=Database
2019-12-09T21:39:57.843Z - verbose: Attempting to bind HTTP server to http://localhost:8000 context=Server
(node:30901) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
2019-12-09T21:39:57.857Z - verbose: HTTP server bound context=Server
2019-12-09T21:39:57.952Z - verbose: Connected to database context=Database
2019-12-09T21:39:57.958Z - verbose: Registering AsinLookup as a service with Consul context=AsinLookup
2019-12-09T21:39:57.958Z - verbose: AsinLookup ready and awaiting requests context=AsinLookup
2019-12-09T21:39:57.958Z - info:    Listening for HTTP requests at http://localhost:8000 context=AsinLookup
2019-12-09T21:40:02.284Z - info:    Incoming request httpVersion=1.1, method=GET, url=/product/B071CV8CG2, host=localhost:8000, user-agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0, accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, accept-language=en-US,en;q=0.5, accept-encoding=gzip, deflate, referer=http://localhost:8000/search, connection=keep-alive, upgrade-insecure-requests=1, 
2019-12-09T21:40:02.289Z - info:    Finding product with asin B071CV8CG2

(node:30901) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'replace' of undefined
    at __puppeteer_evaluation_script__:4:64
    at ExecutionContext._evaluateInternal (/var/www/test/reverseasin/asin_lookup/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/var/www/test/reverseasin/asin_lookup/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async /var/www/test/reverseasin/asin_lookup/route/product.js:28:24
  -- ASYNC --
    at ExecutionContext.<anonymous> (/var/www/test/reverseasin/asin_lookup/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/var/www/test/reverseasin/asin_lookup/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/var/www/test/reverseasin/asin_lookup/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/var/www/test/reverseasin/asin_lookup/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/var/www/test/reverseasin/asin_lookup/node_modules/puppeteer/lib/helper.js:112:23)
    at /var/www/test/reverseasin/asin_lookup/route/product.js:28:35
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:30901) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30901) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by brandynprasad** [comment]
Hello, this was a quick program I put together for a technical assessment (btw, I didn't get the job 😄). I'll admit I never expect anyone to actually use this program! May I ask what you are using it for?

I don't have any imminent plans to maintain this project, but if I find some spare time perhaps I can look into your error some more. 

The node modules have been out of date for quite some time, so perhaps a dependency update will fix your issues? I imagine I'm using a very old version of puppeteer...
